---
title: "3p_binding_greenleaf_tests"
author: "Michael Soutschek"
date: "17 11 2020"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(Biostrings)
  library(ComplexHeatmap)
  library(cowplot)
})
```


# Initialize the models
```{r}
let7a <- read.csv("../../../scanMiR_paper_scripts/3p_binding_Becker_2019/let7a_model_parameters.csv")
mir21 <- read.csv("../../../scanMiR_paper_scripts/3p_binding_Becker_2019/miR21_model_parameters.csv")

m1 <- matrix(let7a$Value..kcal.mol.[grep("^[ACGU]",let7a$Parameter)], nrow=4, byrow = TRUE)
m2 <- matrix(mir21$Value..kcal.mol.[grep("^[ACGU]",mir21$Parameter)], nrow=4, byrow = TRUE)
row.names(m1) <- row.names(m2) <- c("A", "C", "G", "U")
let7a.seq <- unlist(strsplit("UGAGGUAGUAGGUUGUAUAGU",""))
mir21.seq <- unlist(strsplit("UAGCUUAUCAGACUGAUGUUG",""))
colnames(m1) <- paste(1:21,let7a.seq,sep=":")
colnames(m2) <- paste(1:21,mir21.seq,sep=":")

ss <- as.character(complement(RNAStringSet(let7a.seq)))
m1.m <- t(sapply(row.names(m1), FUN=function(x) ifelse(ss==x,"*","")))
m1.m["U",intersect(12:17, which(let7a.seq=="G"))] <- "#"
ss <- as.character(complement(RNAStringSet(mir21.seq)))
m2.m <- t(sapply(row.names(m2), FUN=function(x) ifelse(ss==x,"*","")))
m2.m["U",intersect(12:17, which(mir21.seq=="G"))] <- "#"
```

```{r}
h1 <- Heatmap(-1*m1, cluster_columns=FALSE, name="-kcal/mol", cluster_rows=FALSE, 
        column_title = "let-7a-5p miRNA position (5'->3')", 
        cell_fun=function(j, i, x, y, width, height, fill){
          grid.text(m1.m[i,j], x, y, gp = gpar(fontsize = 15))
})
h2 <- Heatmap(-1*m2, cluster_columns=FALSE, name="-kcal/mol", cluster_rows=FALSE, 
        column_title = "miR-21-5p miRNA position (5'->3')", 
        cell_fun=function(j, i, x, y, width, height, fill){
          grid.text(m2.m[i,j], x, y, gp = gpar(fontsize = 15))
})
plot_grid(
  grid.grabExpr(draw(h1)),
  grid.grabExpr(draw(h2)),
  nrow=2
)
```



