---
title: "Rno_Rims3_overlap"
author: "Michael Soutschek"
date: "2 3 2021"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(scanMiR)
  library(scanMiRApp)
  library(scanMiRData)
  library(ensembldb)
  library(AnnotationHub)
  library(BSgenome)
  library(BiocParallel)
  library(TxDb.Rnorvegicus.UCSC.rn6.refGene)
})
```


# load the annotation
```{r}
genome <- BSgenome.Rnorvegicus.UCSC.rn6::BSgenome.Rnorvegicus.UCSC.rn6

ah <- AnnotationHub()
query(ah, c("NCBI", "Rattus norvegicus"))
txdb <- ah[["AH84143"]]
threeUTRs <- threeUTRsByTranscript(txdb, use.names = TRUE)
```


# Get Rims3 sequence / old annotation
```{r}
Rims3_3UTR <- threeUTRs["NM_022931.1"]
Rims3_3UTR_Seq <- extractTranscriptSeqs(genome, Rims3_3UTR)
```


# Load manually Rims3 new annotation: NM_022931.2
```{r}
Rims3_3UTR_Seq_new <- readDNAStringSet("./NM_022931.2_3UTR_210302.txt")
names(Rims3_3UTR_Seq_new) <- "NM_022931"
```

# Get mods
```{r}
mods <- scanMiRData::getKdModels("rno",NULL)
mods <- KdModelList(mods)
mod138 <- mods[["rno-miR-138-5p"]]
```



# Scanning
```{r}
m_dist0 <- findSeedMatches(Rims3_3UTR_Seq_new,mod138,shadow = 15L,ret = "data.frame",minDist = 0L)
m_dist0$dist <- "min. Distance: 0Nt"

m_dist7 <- findSeedMatches(Rims3_3UTR_Seq_new,mod138,shadow = 15L,ret = "data.frame",minDist = 7L)
m_dist7$dist <- "min. Distance: 7Nt"

m <- rbind(m_dist0,m_dist7)
saveRDS(m,"Rims3_dist.rds")
```


























