---
title: "logKD_Filter"
author: "Michael Soutschek"
date: "30 3 2021"
output: html_document
---






```{r}
suppressPackageStartupMessages({
  library(BiocParallel)
  library(rtracklayer)
  library(GenomicRanges)
  library(ensembldb)
  library(BSgenome.Hsapiens.UCSC.hg19)
  library(org.Hs.eg.db)
  library(data.table)
  library(ggplot2)
  library(tidyverse)
  library(ggsci)
  library(scales)
})
```



# Implement the cutoff into the aggregate_miRNA function
```{r}
aggregateSites <- function(m,ag=-4.863126 , b=0.5735, c=-1.7091, p3=0.04403, 
                           coef_utr = -0.28019,coef_orf = -0.08622, p3.range=c(3L,8L), 
                           keepSiteInfo = FALSE, toInt=FALSE, BP=NULL, cut_off = 0){
  if(is.null(BP)) BP <- BiocParallel::SerialParam()
  if(is(m,"GRanges")){
    m$transcript <- as.factor(seqnames(m))
    m <- mcols(m)
    if(!is.null(m$miRNA)) m$miRNA <- as.factor(m$miRNA)
    m <- as.data.frame(m)
  }
  if(is.null(m$ORF)) m$ORF <- 0L
  if(!is.null(m$miRNA)){
    m <- m[,c("miRNA","transcript","ORF","log_kd","p3.score","type")]
    m <- split(m, m$miRNA)
    m <- bplapply(m, BPPARAM=BP, FUN=function(x){
      aggregate_miRNA(x, ag=ag, b=b, c=c, p3=p3,coef_utr = coef_utr, coef_orf = coef_orf, 
                       keepSiteInfo = keepSiteInfo, toInt=toInt, p3.range=p3.range, 
                      cut_off = cut_off)
    })
    dplyr::bind_rows(m, .id="miRNA")
  }else{
    m <- m[,c("transcript","ORF","log_kd","p3.score","type")]
    m <- aggregate_miRNA(m, ag=ag, b=b, c=c, p3=p3,coef_utr = coef_utr, coef_orf = coef_orf, 
                          keepSiteInfo = keepSiteInfo, toInt=toInt, p3.range=p3.range,
                         cut_off = cut_off)
    m
  }
}


aggregate_miRNA <- function(m,ll = NULL, ag=-4.863126 , b=0.5735, c=-1.7091, p3=0.04403, 
                             coef_utr = -0.28019,coef_orf = -0.08622, p3.range=c(3L,8L), 
                             keepSiteInfo = FALSE, toInt=FALSE, cut_off = -0.3){
  if(is(m,"GRanges")){
    m$transcript <- as.factor(seqnames(m))
    m <- mcols(m)
    if(!is.null(m$miRNA)) m$miRNA <- as.factor(m$miRNA)
    m <- as.data.frame(m)
  }
  if(is.null(m$ORF)) m$ORF <- 0L
  if(!is.null(m$miRNA)){
    m <- m[,c("miRNA","transcript","ORF","log_kd","p3.score","type")]
  }else{
    m <- m[,c("transcript","ORF","log_kd","p3.score","type")]
  }
  m <- as.data.table(m)
  m[, ORF:=as.integer(ORF)]
  m[, log_kd:=-log_kd/1000]
  m <- m[log_kd>0]
  m <- m[log_kd> -cut_off]
  if(keepSiteInfo){
    if(!is.null(m$miRNA)){
      m_type_table <- dcast( m[,.(N=.N), by=c("transcript","miRNA","type")],
                           formula=transcript+miRNA~type, value.var="N", fill=0L)
    }else{
      m_type_table <- dcast( m[,.(N=.N), by=c("transcript","type")],
                             formula=transcript~type, value.var="N", fill=0L)
    }
  }
  if(is.null(m$p3.score)) m$p3.score <- 0L
  m$p3.score <- ifelse(m$type == "non-canonical" , 0L, m$p3.score)
  m$p3.score[m$p3.score>max(p3.range)] <- as.integer(max(p3.range))
  m$p3.score[m$p3.score<min(p3.range)] <- 0L
  m$N <- 1 / (1 + exp(-1 * (ag + m$log_kd + c*m$ORF + p3*m$p3.score) ))
  m$log_kd <- NULL
  m$N_bg <- 1 / (1 + exp(-1 * (ag  + c*m$ORF) ))
  m <- as.data.frame(rowsum(as.matrix(m[,c("N","N_bg")]), group=m$transcript))
  m <- data.frame( transcript=row.names(m),
                   repression=log(1+exp(b)*m$N_bg) - log(1 + exp(b)*m$N) )
  
  if(!is.null(ll) && nrow(m) > 1){
    m <- merge(m,ll,by = "transcript", all.x = TRUE)
    
    # get the utr score
    m$utr_len <- log10(m$utr_len)
    qu_un <- m[!duplicated(m$transcript),"utr_len"]
    qu <- quantile(qu_un, probs = c(0.05,0.95), na.rm = TRUE)
    m$utr_score <- (m$utr_len - qu[1]) / (qu[2] - qu[1])
    
    # get the orf score
    if(sum(m$orf_len) > 0){
      m$orf_len <- log10(m$orf_len)
      qu_un <- m[!duplicated(m$transcript),"orf_len"]
      qu <- quantile(qu_un, probs = c(0.05,0.95), na.rm = TRUE)
      m$orf_score <- (m$orf_len - qu[1]) / (qu[2] - qu[1])
    }else{
      m$orf_score <- 0
    }
  m$repression <- m$repression + coef_utr*m$utr_score*m$repression + coef_orf*m$orf_score*m$repression
  m <- subset(m,select = - c(orf_len,utr_len,utr_score,orf_score))
  }
  if(toInt) m$repression <- as.integer(round(1000*m$repression))
  m$repression <- ifelse(m$repression >= 0, 0, m$repression)
  if(keepSiteInfo){
    if(!is.null(m$miRNA)){
      m <- merge(m, m_type_table, by=c("transcript","miRNA"), all=TRUE)
    }else{
      m <- merge(m, m_type_table, by=c("transcript"), all=TRUE)
    }
  }
  m
}


```






# Helper Functions
```{r}
domnorm <- function(x, useMedian=TRUE){
  y <- setNames(seq_len(ncol(x)), colnames(x))
  if(useMedian){
    x <- as.data.frame(lapply(y, FUN=function(i){
      x[,i]-matrixStats::rowMedians(as.matrix(x[,-i]))
    }), row.names=row.names(x))
  }else{
    x <- as.data.frame(lapply(y, FUN=function(i) x[,i]-rowMeans(x[,-i])), row.names=row.names(x), check.names = FALSE)
  }  
  x
}


getPreds <- function(cut_off=cut_off, m=m, normalize=TRUE, useMedian = FALSE){
  m_agg <- aggregateSites(m = m, cut_off = cut_off)
  m_repr <- pivot_wider(m_agg,id_cols = transcript, names_from = miRNA, values_from = repression, values_fill = list(repression = 0))
  m_repr <- column_to_rownames(m_repr, var = "transcript")
  if(normalize) m_repr <- domnorm(m_repr, useMedian = useMedian)
  m_repr
}

get_cor <- function(cut_off,obs = obs,repr = NULL,mir = mir, mir_names = mir_names, m=NULL,return.raw = FALSE) {
  if(is.null(repr)) repr <- getPreds(cut_off = cut_off, m=m, normalize=TRUE, useMedian = FALSE)
  cor_df <- merge(obs[,mir, drop = FALSE],repr[,mir_names[mir_names == mir], drop = FALSE], by = 0, all.x = TRUE)
  colnames(cor_df) <- c("transcript", "obs","pred")
  cor_df[["pred"]][is.na(cor_df[["pred"]])] <- 0
  if(return.raw) {
    return(cor_df)
  }else{
    cor = cor.test(cor_df$obs, cor_df$pred, method="pearson")
    return(cor$estimate^2)
  }
}


get_cor_vec <- function(cut_vec,mir,m,obs = obs, mir_names) {
  cor_vec <- sapply(cut_vec, get_cor,m = m, mir_names = mir_names, obs = obs, mir = mir)
  return(cor_vec)
} 

```


# Define miRs & load Data
```{r}
# Mir
hek_mirs<- c("hsa-miR-122-5p","hsa-miR-133-3p","hsa-miR-138-5p","hsa-miR-145-5p","hsa-miR-184","hsa-miR-190a-5p","hsa-miR-200b-3p","hsa-miR-216a-5p","hsa-miR-217-5p","hsa-miR-219a-5p","hsa-miR-375-3p","hsa-miR-451a")

# Load Data
m <- readRDS(file = "../../../../Parameter_Optimization/data/hsa.12mirs.HEK.fullScan.GR.rds")
mm <- m
mm$transcript <- as.factor(seqnames(mm))
mm <- split(mcols(mm), mm$miRNA)

ob <- read.delim("../../../../Parameter_Optimization/data/McGeary_2019_raw/GSE140218_HEK293FT_transfection_logtpm_batchnormalized.txt", row.names=1)
ob <- domnorm(ob)
colnames(ob) <- names(mm)
```



# Get the cut_off correlation for mir122
```{r}
cut_vec <- seq(-2,0, length.out = 40)
mir122 <- "hsa-miR-122-5p"

cor <- get_cor_vec(cut_vec, mir = mir122,m = m, mir_names = hek_mirs, obs = ob)
cor_df <- data.frame(cut_off = cut_vec, r2=cor)
cor_df1 <- cor_df
cor_df1$mir <- "hsa-miR-122-5p"

ggplot(cor_df1, aes(x = cut_off, y = r2)) + 
  geom_line(size = 1) +
  theme_bw() +
  ylab('r^2') +
  xlab("logKD cut-off") +
  ggtitle("miR-122-5p")

ggsave("cut_off_correlation_mir122.png")
gc()
```



# Get the cut_off correlation for mir138
```{r}
cut_vec <- seq(-2,0, length.out = 40)
mir138 <- "hsa-miR-138-5p"

cor <- get_cor_vec(cut_vec, mir = mir138,m = m, mir_names = hek_mirs, obs = ob)
cor_df <- data.frame(cut_off = cut_vec, r2=cor)
cor_df2 <- cor_df
cor_df2$mir <- "hsa-miR-138-5p"

ggplot(cor_df2, aes(x = cut_off, y = r2)) + 
  geom_line(size = 1) +
  theme_bw() +
  ylab('r^2') +
  xlab("logKD cut-off") +
  ggtitle("miR-138-5p")

ggsave("cut_off_correlation_mir138.png")
gc()
```



# Get the cut_off correlation for mir216a
```{r}
cut_vec <- seq(-2,0, length.out = 40)
mir216 <- "hsa-miR-216a-5p"

cor <- get_cor_vec(cut_vec, mir = mir216,m = m, mir_names = hek_mirs, obs = ob)
cor_df <- data.frame(cut_off = cut_vec, r2=cor)
cor_df3 <- cor_df
cor_df3$mir <- "hsa-miR-216a-5p"

ggplot(cor_df3, aes(x = cut_off, y = r2)) + 
  geom_line(size = 1) +
  theme_bw() +
  ylab('r^2') +
  xlab("logKD cut-off") +
  ggtitle("hsa-miR-216a-5p")

ggsave("cut_off_correlation_mir216a.png")
gc()
```

#combined plot
```{r}
df <- rbind(cor_df1,cor_df2,cor_df3)
saveRDS(df,"PlotDF.rds")
```

```{r}
df <- readRDS("PlotDF.rds")

ggplot(df, aes(x = cut_off, y = r2)) + 
  geom_line(size = 1) +
  theme_bw() +
  ylab('r^2') +
  xlab("logKD cut-off") +
  facet_grid(~mir)

ggsave("CombinedPlot.png",width = 12,height = 7)
```



# Get all cut-off values
```{r}
# get optimal for all mirs
cut_off_list <- list()
cut_vec <- seq(-2,0, length.out = 40)
for(mirna in hek_mirs) {
  cor <- get_cor_vec(cut_vec, mir = mirna,m = m, mir_names = hek_mirs, obs = ob)
  cor_df <- data.frame(cut_off = cut_vec, r2=cor)
  cor_df <- cor_df[which(cor_df$r2 > 0.975*max(cor_df$r2)),]
  cut_off <- min(cor_df$cut_off)
  cut_off_list[[mirna]]["cutoff"] <- cut_off
}

saveRDS(cut_off_list,"cut_off_list_97.rds")



# get optimal for all mirs
cut_off_list <- list()
cut_vec <- seq(-2,0, length.out = 40)
for(mirna in hek_mirs) {
  cor <- get_cor_vec(cut_vec, mir = mirna,m = m, mir_names = hek_mirs, obs = ob)
  cor_df <- data.frame(cut_off = cut_vec, r2=cor)
  cor_df <- cor_df[which(cor_df$r2 > 0.99*max(cor_df$r2)),]
  cut_off <- min(cor_df$cut_off)
  cut_off_list[[mirna]]["cutoff"] <- cut_off
}

saveRDS(cut_off_list,"cut_off_list_99.rds")
```


# Cut_Off List Figure
```{r}
cut97 <- readRDS("cut_off_list_97.rds")
cut99 <- readRDS("cut_off_list_99.rds")

cut97 <- data.frame(miRNA = names(cut97), "Cut-off 97" = unlist(cut97))
cut99 <- data.frame(miRNA = names(cut99), "Cut-off 99" = unlist(cut99))

cut_df <- merge(cut97,cut99, by = "miRNA")
cut_df$Cut.off.97 <- round(cut_df$Cut.off.97,4)
cut_df$Cut.off.99 <- round(cut_df$Cut.off.99,4)
colnames(cut_df) <- c("miRNA","Cut-off 97.5%","Cut-off 99%")
saveRDS(cut_df,"Plot_Table_cut_df.rds")

ft <- flextable(cut_df)
ft <- autofit(ft)
```




# To do a pie chart
```{r}
e <- as.data.frame(mcols(m))
e$transcript <- as.factor(seqnames(m))
e <- as.data.table(e)

cut_off <- nrow(e[e$log_kd > -300,])/nrow(e)
rest <- 1 - nrow(e[e$log_kd > -300,])/nrow(e)

df <- data.frame("cut" = cut_off , "rest" = rest)
df <- data.frame(t(df))
df$group <- c("Cut-off at -0.3","All other sites")


blank_theme <- theme_minimal()+
  theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.border = element_blank(),
  panel.grid=element_blank(),
  axis.ticks = element_blank(),
  plot.title=element_text(size=14, face="bold"),
  legend.title = element_blank()
  )

pie <- ggplot(df, aes(x="", y=t.df., fill=group))+
  geom_bar(width = 1, stat = "identity") + 
  coord_polar("y", start=0) + 
  scale_fill_nejm(alpha = 0.8) +
  blank_theme 

pie <- pie + theme(axis.text.x=element_blank()) + 
  geom_text(aes(y = t.df./2 + c(0, cumsum(t.df.)[-length(t.df.)]), 
                label = percent(t.df./100)), size=5)

pie
ggsave("PieChart.png")
```


