---
title: "hlncRNA_scan"
author: "Michael Soutschek"
date: "26 2 2021"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(scanMiR)
  library(scanMiRData)
  library(ensembldb)
  library(AnnotationHub)
  library(BSgenome)
  library(BiocParallel)
})
```



# Get lncRNA sequences
```{r}
# Prepare
ah <- AnnotationHub()
genome <- BSgenome.Hsapiens.UCSC.hg38::BSgenome.Hsapiens.UCSC.hg38
ahid <- rev(query(ah, c("EnsDb", "Homo sapiens"))$ah_id)[1]
ensdb <- ah[[ahid]]
seqlevelsStyle(genome) <- "Ensembl"

# restrict to canonical chromosomes
canonical_chroms <- seqlevels(genome)[!grepl('_', seqlevels(genome))]

# Get Sequences
filt <- SeqNameFilter(canonical_chroms)
## listTxbiotypes(ensdb)
grl_lncRNA <- ensembldb::exonsBy(ensdb, by = "tx", filter = ~ tx_biotype == "lncRNA" & filt)
seqs_lncRNA <- extractTranscriptSeqs(genome,grl_lncRNA )

# Get Info
info <- data.frame(strand=unlist(unique(strand(grl_lncRNA))))
lncRNA.len <- lengths(seqs_lncRNA)
info$lncRNA.length <- lncRNA.len[row.names(info)]
mcols(seqs_lncRNA)$lncRNA.length <- lncRNA.len[names(seqs_lncRNA)]
```

# Get mods
```{r}
mods <- scanMiRData::getKdModels("hsa",c("Conserved across mammals","Conserved across vertebrates"))
mods <- KdModelList(mods)
```


# Screen for Cyrano
```{r}
Cyr <- seqs_lncRNA[names(seqs_lncRNA) == "ENST00000500949"]
mods.7 <- mods[["hsa-miR-7-5p"]]
m.Cyr <- findSeedMatches(Cyr, mods.7, shadow=0L,p3.extra = TRUE, BP=MulticoreParam(12, progress=TRUE),keepMatchSeq = TRUE)
saveRDS(m.Cyr,"../Figures/Figure_4/Cyrano_miR7.rds")
```





# Scan
```{r}
# m <- findSeedMatches(seqs_lncRNA, mods, shadow=0L,ret = "GRanges",p3.extra = TRUE, BP=MulticoreParam(12, progress=TRUE))
# saveRDS(m,"human_lncRNAs_cons.miRNAs.rds")
```


# Filter for TDMD sites
```{r}
# m_TDMD <- m[m$note != "-"]
# saveRDS(m_TDMD,"human_lncRNAs_cons.miRNAs_TDMD.rds")
```




