---
title: "archetypes"
author: "Pierre-Luc Germain"
date: "2/23/2021"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(scanMiR)
  library(scanMiRData)
  library(ggplot2)
  library(ggrepel)
  library(cowplot)
  library(ggpointdensity)
  library(viridis)
  library(ggpubr)
})
theme_set(theme_cowplot(font_size=12, rel_large=15/14))
```

#colors
```{r}
source("../misc.R")
```



```{r}
set.seed(1234)
mods <- getKdModels("hsa",categories = NULL)
kd <- read.delim("/mnt/schratt/scanMiR_paper_scripts_old/Parameter_Optimization/data/CNN/hsa-miR-122-5p_kds.txt", colClasses = c(X12mer="character", log_kd="numeric", mir="factor", "mirseq"="factor", "aligned_type"=NULL, "best_stype"=NULL))
mod <- getKdModel(kd)
kd <- kd[grep("X",kd$X12mer,invert=TRUE),]
kd2 <- assignKdType(kd$X12mer, mod)
kd$compressed <- kd2$log_kd/1000
kd1 <- kd[sample.int(nrow(kd), 100000),]

d <- data.frame(row.names=names(mods), conservation=conservation(mods),
                correlation=sapply(mods,FUN=function(x) x$cor),
                toplogKd=sapply(mods,FUN=function(x) min(x$mer8/1000)))
d2 <- d[which(as.integer(d$conservation)>2),]
d2 <- d2[order(abs(d2$correlation-mean(d2$correlation))),]

kd <- read.delim("/mnt/schratt/enrichMiR_data/miRNA_KD_CNN/predictions/hsa/hsa-miR-24-3p_kds.txt", colClasses = c(X12mer="character", log_kd="numeric", mir="factor", "mirseq"="factor", "aligned_type"=NULL, "best_stype"=NULL))
mod <- getKdModel(kd)
kd <- kd[grep("X",kd$X12mer,invert=TRUE),]
kd2 <- assignKdType(kd$X12mer, mod)
kd$compressed <- kd2$log_kd/1000
kd2 <- kd[sample.int(nrow(kd), 100000),]

kd <- rbind(kd1, kd2)
kd$residual <- kd$log_kd-kd$compressed
kd$X12mer <- kd$mirseq <- NULL
p1a <- ggplot(kd, aes(x=log_kd, y=compressed) ) + 
  ggrastr::rasterize(geom_pointdensity(size=0.8, show.legend=FALSE), dpi=150) +
  labs(x=bquote("Original"~log(K[D])), y=bquote("Reconstituted"~log(K[D]))) +
  scale_colour_viridis() + theme(legend.position = "top") + 
  geom_text(data=data.frame(x=-4.8,y=2,mir=unique(kd$mir),label=paste0("r=",round(c(cor(kd1$log_kd,kd1$compressed),cor(kd2$log_kd,kd2$compressed)),3))), aes(x=x,y=y,label=label)) +
  facet_wrap(~mir, nrow=1)

p1aj <- ggplot(kd, aes(x=log_kd, y=residual) ) +
    ggrastr::rasterize(geom_pointdensity(size=0.8, show.legend=FALSE), dpi=150) +
    labs(x=bquote("Original"~log(K[D])), y="Residuals") +
    scale_colour_viridis() + facet_wrap(~mir, nrow=1) +
    theme(legend.position="none", strip.background = element_blank(), strip.text.x = element_blank())
p1 <- ggarrange(p1a + theme(axis.title.x = element_blank()), p1aj, nrow = 2, heights = c(5,3), align = "v")

p1b <- ggplot(d, aes(correlation, toplogKd)) + geom_pointdensity(show.legend=FALSE) + scale_colour_viridis() + labs(x="Correlation with original", y=bquote("Strongest "~log(K[D]))) +
  geom_vline(xintercept=c(cor(kd1$log_kd,kd1$compressed),cor(kd2$log_kd,kd2$compressed)), linetype="dashed")
p1b <- ggExtra::ggMarginal(p1b, type="histogram", margins="x", fill="darkblue", size=4)

#plot_grid(p1a, p1b, labels="AUTO", rel_widths = c(5,2), scale=0.95)
```


```{r}
mods <- getKdModels("hsa", categories = NULL)

ms <- t(sapply(mods, FUN=function(mod, n=15){
  mer8 <- getSeed8mers(mod$canonical.seed)
  wA <- which(substr(mer8,8,8)=="A")
  mer7 <- substr(mer8,1,7)
  As <- mod$mer8[wA]
  names(As) <- mer7[wA]
  mer.mean <- rowsum(mod$mer8[-wA],mer7[-wA])[,1]/3
  As <- As-mer.mean[names(As)]
  d <- data.frame(seed=names(mer.mean), base=mer.mean/-1000, "A"=As[names(mer.mean)]/-1000,
                  type=getMatchTypes(names(mer.mean),mod$canonical.seed), row.names=NULL)
  d <- d[head(order(d$base, decreasing=TRUE),n=n),]
  d$seed <- factor(as.character(d$seed), rev(as.character(d$seed)))
  levels(d$type) <- scanMiR:::.matchLevels(FALSE)
  gini <- ineq::Gini(1/10^(d$base))
  ent <- entropy::entropy(1/10^(d$base))
  topNC <- d[grep("g-bulged|non-canonical",d$type)[1],2]
  d <- aggregate(d[,2,drop=FALSE], by=list(type=d[,4]), na.rm=TRUE, FUN=median)
  d <- setNames(c(d[,2],topNC),c(as.character(d[,1]),"topNC"))
  c(d[c("7mer","6mer","g-bulged 6mer","6mer-m8","topNC","non-canonical")], entropy=ent, gini=gini)
}))
colnames(ms) <- c("m7","m6","gb_6mer","6mer_m8","topNC","median10NCs","entropy","gini")
ms <- as.data.frame(ms)
ms$diff7 <- ms$m7-ms$m6
ms$diff6 <- ms$m6-ms$topNC
ms$diffNC <- ms$topNC-ms$median10NCs
mod <- loess(ms$topNC~ms$m7)
ms$topNC.dev <- ms$topNC - mod$fitted
ms$miRNA <- row.names(ms)
```

```{r, fig.width=9, fig.height=4}
# check for relation of the correlation with seed complexity
ms$mirseq <- sapply(mods, FUN=function(x) x$mirseq)[row.names(ms)]
ms$mir.entropy <- acss::entropy(ms$mirseq)
ms$seed7 <- sapply(mods, FUN=function(x) substr(x$canonical.seed,1,7))[row.names(ms)]
ms$cor <- sapply(mods, FUN=function(x) x$cor)[row.names(ms)]
ms$seed7.entropy <- acss::entropy(ms$seed7)
ms$seed7.entropy2 <- as.factor(round(ms$seed7.entropy,2))
ms$seed.GC <- nchar(gsub("A|T","",ms$seed7))/7
sp1 <- ggplot(ms, aes(seed7.entropy2, cor)) + geom_boxplot() +
  labs(x="Seed entropy", y="Correlation")
sp2 <- ggplot(ms, aes(as.factor(round(seed.GC,2)), cor)) + geom_boxplot() + 
  ylab("Correlation") + xlab("Proportion of G/C in seed")
plot_grid(sp1,sp2)
```



```{r, fig.width=11, fig.height=6}
mirs <- c("hsa-miR-199a-5p","hsa-miR-124-3p", "hsa-miR-499a-5p")
#mirs <- c("hsa-miR-7-5p","hsa-miR-124-3p", "hsa-miR-499a-5p")
#mirs <- c("hsa-miR-495-3p", "hsa-miR-124-3p", "hsa-miR-92b-5p")
#mirs <- c("hsa-miR-214-5p","hsa-miR-124-3p", "hsa-miR-155-5p","hsa-miR-199a-5p")
p2 <- ggplot(ms, aes(m6, topNC)) + geom_abline(slope=1, colour="grey") + 
  geom_point(aes(colour=gini)) + 
  geom_label_repel(data=ms[mirs,], aes(label=miRNA), nudge_x=c(-0.75,-0.75,0.8), 
                   min.segment.length = 0, segment.color = "black", segment.size= 1) + 
  labs(x=bquote("median -"*log(K[D])*" of 6mers"), y=
         bquote(atop("-"*log(K[D])*" of top","non-canonical")), 
       colour=bquote(atop("Gini"~(K[D])~"of", "top 15 k-mers"))) + 
  #theme(legend.position = "bottom") +
  scale_colour_viridis(breaks=scales::pretty_breaks(3))

ps <- lapply(mirs, FUN=function(x){
  p <- plotKdModel(mods[[x]], what = "seeds") + 
    theme(axis.text.y = element_text(family="mono"), 
          plot.title=element_text(hjust=0),
          plot.subtitle=element_text(family="mono", size=10, hjust=1))
    # scale_fill_manual(values=c("7mer"= darkgreen, "6mer"="#4477AA",
    #                             "g-bulged 6mer"="#117733", "+A"="darkred",
    #                             "non-canonical"=light,
    #                            "g-bulged 7mer"= turquoise))
  p + scale_fill_manual(values = type_cols[p$data$type])
})
leg <- ggpubr::get_legend(ps[[2]])
ps <- lapply(ps, FUN=function(x) x + theme(legend.position = "none"))

row1 <- plot_grid(p1, plot_grid(p1b, p2, nrow=2, labels=c("B","C")), nrow=1, 
                  scale=0.95, labels=c("A",NULL))
row2 <- plot_grid(ps[[3]], ps[[2]], ps[[1]], leg, nrow=1, rel_widths=c(2,2,2,0.8),
                  labels=LETTERS[4:6], scale=0.95)
pp <- plot_grid( row1, row2, nrow=2, rel_heights=c(6,4))

ggsave("Figure_2.png", pp, height=7, width=11, bg="white")
ggsave("Figure_2.pdf", pp, height=7, width=11, bg="white")

```

